[libdefaults]
    default_realm = EXAMPLE.TEST
    dns_lookup_realm = false
    dns_lookup_kdc = true
    rdns = false
    forwardable = true
    kdc_timesync = 1
    ccache_type = 4

[domain_realm]
    .example.test = EXAMPLE.TEST
    example.test = EXAMPLE.TEST
