[global]
    workgroup = STUMPFWORKS
    realm = EXAMPLE.TEST
    security = ADS
    kerberos method = secrets and keytab

    winbind use default domain = yes
    winbind offline logon = yes
    winbind refresh tickets = yes
    winbind enum users = no
    winbind enum groups = no
    template homedir = /home/%U
    template shell = /bin/bash

    idmap config * : backend = tdb
    idmap config * : range = 3000-7999
    idmap config STUMPFWORKS : backend = rid
    idmap config STUMPFWORKS : range = 10000-999999

    log file = /var/log/samba/log.%m
    max log size = 1000
    logging = file
