[kdc]
enable-pkinit = yes
pkinit_identity = FILE:/var/lib/samba/private/pkinit/dc01-kdc.crt,/var/lib/samba/private/pkinit/dc01-kdc.key
pkinit_anchors = FILE:/var/lib/samba/private/pkinit/pkinit-ca.crt
