[libdefaults]
	default_realm = EXAMPLE.TEST
	dns_lookup_realm = false
	dns_lookup_kdc = true

[realms]
EXAMPLE.TEST = {
	default_domain = example.test
}

[domain_realm]
	dc01 = EXAMPLE.TEST

[kdc]
	enable-pkinit = yes
	pkinit_identity = FILE:/var/lib/samba/private/pkinit/dc01-kdc.crt,/var/lib/samba/private/pkinit/dc01-kdc.key
	pkinit_anchors = FILE:/var/lib/samba/private/pkinit/pkinit-ca.crt
